name: Build & Deploy
on:  
  push:
    branches: [ main ]
jobs:  
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    steps:   
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Restaurant Advanced App     
        uses: actions/checkout@v2
      - name: Connects to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           host: ${{ secrets.HOST }}
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          #          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRI_KEY }} 
                    
          script:
             sudo cp -r github-pipeline-deploy-static-website-ubuntu/index.html /var/www/html/site1/
